version: 0.2

env:
  REACT_APP_CONFORMATION_EMAIL_REDIRECT: /webportal/front-end/REACT_APP_CONFORMATION_EMAIL_REDIRECT
  REACT_APP_GRAPHQL_ENDPOINT: /webportal/front-end/REACT_APP_GRAPHQL_ENDPOINT
  REACT_APP_GRAPHQL_WS_ENDPOINT: /webportal/front-end/REACT_APP_GRAPHQL_WS_ENDPOINT
  REACT_APP_PASSWORD_FORGOT_REDIRECT: /webportal/front-end/REACT_APP_PASSWORD_FORGOT_REDIRECT
  REACT_APP_REST_ENDPOINT: /webportal/front-end/REACT_APP_REST_ENDPOINT

phases:
  install:
    run-as: root
    runtime-versions:
      nodejs: 10
    commands:
      - echo Entered the install phase ...
      - yum update -y
      - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
      - npm install
  pre_build:
    run-as: root
    commands:
      - echo Entered the pre_build phase ...
  build:
    run-as: root
    commands:
      - echo Entered the build phase ...
      - echo Build started on `date`
      - npm run build
  post_build:
    run-as: root
    commands:
      - echo Entered the post_build phase ...
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  base-directory: build
